@extends('layouts.default')
@section('content')
    @include('contents.instructions')
    @include('contents.create-campaign-form')
    @include('contents.get-campaign-form')
    @include('contents.pause-campaign-form')
    @include('contents.delete-campaign-form')
    @include('contents.show-report-form')
@endsection